name: 'Exercicio 2"

on:
  push:
  
jobs:

  cria_upload_artefato:
    name: Cria artefato e faz upload
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
        
      - name: Upload build artefato
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ vars.NOME_ARQUIVO_UPLOAD }}
          path: .
          retention-days: 15
